version: '3.8'
name: bbdd_cjy
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fakeAcessKey
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'
    ports:
      - '8000:8000'
    volumes:
      - ./data:/data
    networks:
      - bbdd

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - bbdd

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - bbdd
    depends_on:
      - elasticsearch

networks:
  bbdd:
    name: bbdd

volumes:
  db:
    driver: local
